Repository Nice-HUD/Nice-HUD, pull requests merged in 2024-10, with the labels that each got.

#21 Feature/20 indicate enemies number
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  src/HUDTeam/DrawManagerImpl.java
  src/screen/GameScreen.java
Labels: feature

#34 [Hotfix]: restore .idea files and Update .gitignore
  .gitignore
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  src/twoplayermode/PlayerShip.java
  src/twoplayermode/TwoPlayerMode.java
Labels: bug

#32 feat: replace the attack speed and movement speed position
  src/HUDTeam/DrawManagerImpl.java
Labels: enhencement

#40 Feature/39 replace attack speed with bullet speed
  Invaders-SDP-Team-International-.iml
  src/HUDTeam/DrawManagerImpl.java
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: enhencement

#45 fix: bullet speed notation error
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: bug

#47 feat : Feature add the status information of 2p
  src/HUDTeam/DrawManagerImpl.java
  src/engine/DrawManager.java
  src/screen/GameScreen.java
  src/twoplayermode/TwoPlayerMode.java
Labels: enhencement

#49 feat: Change player ships colors
  src/entity/Ship.java
  src/screen/GameScreen.java
  src/twoplayermode/TwoPlayerMode.java
Labels: enhencement

#50 HUD function development v1.0
  src/HUDTeam/DrawManagerImpl.java
  src/engine/DrawManager.java
  src/entity/Ship.java
  src/screen/GameScreen.java
  src/twoplayermode/TwoPlayerMode.java
Labels: enhencement
